name: Node.js CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Test and build (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.18.x', '24.11.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build development bundle
        run: npm run build-dev

      - name: Build production bundle
        run: npm run build-prod
